name: Publish
on:
  push:
    tags:
      # explicitly only publishing v0.* tags for now
      - v0.*.* # 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - "src/**/*.ts"
      - "!src/**/*.test.ts"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
